# Generated by Django 4.0.2 on 2022-03-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call_logs',
            fields=[
                ('unique_id', models.CharField(max_length=255)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_number', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('call_type', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('sales_agent_number', models.CharField(max_length=255)),
                ('sales_agent_email', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
